const Products = [
	{
		name: "Τρυπάνι SDS 8 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 10 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 12 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 14 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 16 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 18 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 20 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 22 mm",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YD8vXO.webp",
	},
	{
		name: "Τρυπάνι SDS 8 mm τετράκοπο",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJ9rC.webp",
	},
	{
		name: "Τρυπάνι SDS 10 mm τετράκοπο",
		description: "",
		category: "Τρυπάνι SDS",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJ9rC.webp",
	},
	{
		name: "Τρυπάνι Μαύρο Αέρος",
		description: "Τρυπάνι ακίδος για ξύλο της Benman. Τρύπημα ακριβείας χάρη στην ακίδα κεντραρίσματος, τις δύο κοπτικές ακμές και την διπλή ελίκωση που διαθέτει. Προσφέρει γρήγορη διάτρηση, χωρίς φθορές στο ξύλο. Κατασκευασμένο σύμφωνα με τα πρότυπα DIN8037. Κατάλληλο για ξύλο, μελαμίνη, και κόντρα-πλακέ.",
		category: "Τρυπάνι Αέρος",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJRme.webp",
	},
	{
		name: "Διαμαντοτρύπανο Benman",
		description: "Κατάλληλο για τοίχους, πέτρα, τούβλα και μπετόν.",
		category: "Διαμαντοτρύπανο",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJt1M.webp",
	},
	{
		name: "Τρυπάνι Γυαλιού",
		description: "Τρυπάνι ειδικό για γυαλί και πλακάκια.",
		category: "Τρυπάνι Γυαλιού",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJWWd.webp",
	},
	{
		name: "Διαμαντοτρύπανο Καρβιδίου",
		description: "Με κυλινδρικό στέλεχος. Κατάλληλο για χρήση με & χωρίς κρούση. Ειδικά σχεδιασμένο καρβίδιο για μεγαλύτερη ταχύτητα, αντοχή στη φθορά και σχεδιασμένο σπιράλ για άριστο τρύπημα. Για γρανίτες, μάρμαρα και πολύ δυνατά υλικά.",
		category: "Διαμαντοτρύπανο",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJLPh.webp",
	},
	{
		name: "Τρυπάνι Ακίδος με Κυλινδρικό Στέλεχος",
		description: "Τρυπάνι ακίδος για ξύλο της Benman. Τρύπημα ακριβείας χάρη στην ακίδα κεντραρίσματος, τις δύο κοπτικές ακμές και την διπλή ελίκωση που διαθέτει. Προσφέρει γρήγορη διάτρηση, χωρίς φθορές στο ξύλο.",
		category: "Τρυπάνι Ακίδος",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJFrO.webp",
	},
	{
		name: "Τρυπάνι Κοβαλτίου",
		description: "",
		category: "Τρυπάνι Κοβαλτίου",
		amount: "",
		image: "https://s6.imgcdn.dev/YDJHqn.webp",
	},
]